//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamWAD.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Exam
    {
        public int ID { get; set; }

        [Display(Name = "Exam Subject")]
        public int Subject { get; set; }

        [Display(Name = "Start Time")]
        [DataType(DataType.Time)]
        public System.TimeSpan StartTime { get; set; }

        [Display(Name = "Exam Date")]
        [DataType(DataType.Date)]
        public System.DateTime ExamDate { get; set; }

        [Display(Name = "Exam Duration")]
        [Required(ErrorMessage = "Ban chua nhap duration.")]
        public int Duration { get; set; }

        [Display(Name = "Class Room")]
        public int ClassRoom { get; set; }

        [Display(Name = "Faclty")]
        public int Faculty { get; set; }

        public int Status { get; set; }
    }
}
